import os
from textblob import TextBlob
from deep_translator import GoogleTranslator
from google import genai
from google.genai import types
from groq import Groq
from langdetect import detect
from dotenv import load_dotenv

load_dotenv()

# 🌟 INITIALIZE BRAIN 1 (Google Gemini)
try:
    gemini_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
except Exception as e:
    print(f"⚠️ Failed to initialize Gemini: {e}")
    gemini_client = None

# 🌟 INITIALIZE BRAIN 2 (Groq / Llama 3)
try:
    groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
except Exception as e:
    print(f"⚠️ Failed to initialize Groq: {e}")
    groq_client = None

def analyze_deep_emotion(user_text):
    # 🌟 100% OFFLINE EMOTION ENGINE
    text = user_text.lower()
    
    emotions = {
        'joy': 0.1, 'surprise': 0.1, 'neutral': 0.5, 
        'sadness': 0.1, 'fear': 0.1, 'disgust': 0.1, 'anger': 0.1
    }
    
    sad_words = ['sad', 'down', 'depressed', 'demotivated', 'cry', 'lonely', 'tired', 'hopeless', 'bad', 'hurt']
    joy_words = ['happy', 'good', 'great', 'joy', 'motivated', 'excited', 'awesome', 'love', 'smile']
    fear_words = ['scared', 'anxious', 'fear', 'terrified', 'nervous', 'panic', 'worry', 'stress']
    anger_words = ['angry', 'mad', 'frustrated', 'hate', 'annoyed', 'furious', 'irritated']
    surprise_words = ['wow', 'omg', 'amazed', 'shocked', 'sudden', 'unexpected']
    disgust_words = ['gross', 'disgusting', 'sick', 'vile', 'awful']

    if any(w in text for w in sad_words): emotions['sadness'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in joy_words): emotions['joy'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in fear_words): emotions['fear'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in anger_words): emotions['anger'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in surprise_words): emotions['surprise'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in disgust_words): emotions['disgust'] += 0.8; emotions['neutral'] = 0.1

    total = sum(emotions.values())
    result = [{"label": k, "score": v / total} for k, v in emotions.items()]
    return result

CRISIS_KEYWORDS = ["die", "suicide", "kill", "end my life", "hopeless", "end it", "worthless", "give up", "dead"]

def detect_crisis(user_text):
    try:
        english_translation = GoogleTranslator(source='auto', target='en').translate(user_text)
        return any(keyword in english_translation.lower() for keyword in CRISIS_KEYWORDS)
    except:
        return any(keyword in user_text.lower() for keyword in CRISIS_KEYWORDS)

def analyze_sentiment(text):
    try:
        english_translation = GoogleTranslator(source='auto', target='en').translate(text)
        polarity = TextBlob(english_translation).sentiment.polarity
        if polarity > 0.1: return "positive"
        elif polarity < -0.1: return "negative"
        else: return "neutral"
    except:
        return "neutral"

def generate_ai_response(user_input, chat_history, user_lang='en'):
    # 1. Translate TO English
    if user_lang != 'en':
        try:
            english_input = GoogleTranslator(source=user_lang, target='en').translate(user_input)
        except:
            english_input = user_input
    else:
        english_input = user_input

    # 2. Format History
    history_text = "\n".join([f"{msg['role']}: {msg['text']}" for msg in chat_history[-3:]])
    system_prompt = "You are SafeMinds, a warm, highly empathetic mental health and well-being companion."
    
    enforced_input = f"""
    Past Conversation:
    {history_text}
    
    User's New Message: "{english_input}"
    
    Task: Reply as SafeMinds.
    
    STRICT BOUNDARY RULES:
    1. You ONLY discuss mental health, emotional well-being, personal struggles, and coping strategies.
    2. IF the user asks about trivia, coding, politics, math, or general knowledge, YOU MUST REFUSE nicely and pivot back to their feelings.
    3. Keep your reply under 2 short sentences (Max 25 words).
    """

    english_reply = ""

    #  pLAN A: Try Gemini First
    try:
        if not gemini_client: raise ValueError("Gemini offline.")
        
        response = gemini_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=enforced_input,
            config=types.GenerateContentConfig(system_instruction=system_prompt, temperature=0.7)
        )
        english_reply = response.text
        print("✅ Response generated by: GEMINI")

    except Exception as gemini_error:
        print(f"⚠️ Gemini Failed ({gemini_error}). Initiating Groq Failover...")
        
        #  PLAN B: Gemini failed! Immediately try Groq.
        try:
            if not groq_client: raise ValueError("Groq offline.")
            
            chat_completion = groq_client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": enforced_input}
                ],
               model="llama-3.1-8b-instant", # Using Meta's newest Llama 3.1 model, # Using Meta's newest Llama 3.1 model, # Using Meta's fast Llama 3 model
                temperature=0.7,
                max_tokens=60
            )
            english_reply = chat_completion.choices[0].message.content
            print("✅ Response generated by: GROQ (FAILOVER SUCCESS)")
            
        except Exception as groq_error:
            # 💥 PLAN C: Both APIs are down. Show fallback message.
            print(f"❌ Groq also failed: {groq_error}")
            english_reply = "I am having a connection issue right now. Please remember you are not alone."

    # 3. Clean up and Translate Back
    if english_reply:
         english_reply = english_reply.replace('*', '').strip()
         
    if user_lang != 'en' and "connection issue" not in english_reply:
        try:
            return GoogleTranslator(source='en', target=user_lang).translate(english_reply)
        except:
            pass
            
    return english_reply