import os
from textblob import TextBlob
from deep_translator import GoogleTranslator
from openai import OpenAI
from langdetect import detect
from dotenv import load_dotenv

load_dotenv()

# 🌟 100% PURE GEMMA BRAIN (Via OpenRouter)
try:
    gemma_client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=os.getenv("OPENROUTER_API_KEY") 
    )
    print("✅ Pure Gemma AI Initialized")
except Exception as e:
    print(f"⚠️ Failed to initialize OpenRouter: {e}")
    gemma_client = None

def analyze_deep_emotion(user_text):
    text = user_text.lower()
    
    emotions = {
        'joy': 0.1, 'surprise': 0.1, 'neutral': 0.5, 
        'sadness': 0.1, 'fear': 0.1, 'disgust': 0.1, 'anger': 0.1
    }
    
    sad_words = ['sad', 'down', 'depressed', 'demotivated', 'cry', 'lonely', 'tired', 'hopeless', 'bad', 'hurt']
    joy_words = ['happy', 'good', 'great', 'joy', 'motivated', 'excited', 'awesome', 'love', 'smile']
    fear_words = ['scared', 'anxious', 'fear', 'terrified', 'nervous', 'panic', 'worry', 'stress']
    anger_words = ['angry', 'mad', 'frustrated', 'hate', 'annoyed', 'furious', 'irritated']
    surprise_words = ['wow', 'omg', 'amazed', 'shocked', 'sudden', 'unexpected']
    disgust_words = ['gross', 'disgusting', 'sick', 'vile', 'awful']

    if any(w in text for w in sad_words): emotions['sadness'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in joy_words): emotions['joy'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in fear_words): emotions['fear'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in anger_words): emotions['anger'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in surprise_words): emotions['surprise'] += 0.8; emotions['neutral'] = 0.1
    if any(w in text for w in disgust_words): emotions['disgust'] += 0.8; emotions['neutral'] = 0.1

    total = sum(emotions.values())
    result = [{"label": k, "score": v / total} for k, v in emotions.items()]
    return result

CRISIS_KEYWORDS = ["die", "suicide", "kill", "end my life", "hopeless", "end it", "worthless", "give up", "dead"]

def detect_crisis(user_text):
    try:
        english_translation = GoogleTranslator(source='auto', target='en').translate(user_text)
        return any(keyword in english_translation.lower() for keyword in CRISIS_KEYWORDS)
    except:
        return any(keyword in user_text.lower() for keyword in CRISIS_KEYWORDS)

def analyze_sentiment(text):
    try:
        english_translation = GoogleTranslator(source='auto', target='en').translate(text)
        polarity = TextBlob(english_translation).sentiment.polarity
        if polarity > 0.1: return "positive"
        elif polarity < -0.1: return "negative"
        else: return "neutral"
    except:
        return "neutral"

def generate_ai_response(user_input, chat_history, user_lang='en'):
    if user_lang != 'en':
        try:
            english_input = GoogleTranslator(source='auto', target='en').translate(user_input)
        except:
            english_input = user_input
    else:
        english_input = user_input

    english_history = []
    for msg in chat_history[-3:]:
        try:
            en_text = GoogleTranslator(source='auto', target='en').translate(msg['text'])
        except:
            en_text = msg['text']
        english_history.append(f"{msg['role']}: {en_text}")
        
    history_text = "\n".join(english_history)
    
    system_prompt = "You are SafeMinds, a warm, highly empathetic mental health and well-being companion."
    
    enforced_input = f"""
    Past Conversation:
    {history_text}
    
    User's New Message: "{english_input}"
    
    Task: Reply as SafeMinds.
    
    STRICT BOUNDARY RULES:
    1. You ONLY discuss mental health, emotional well-being, personal struggles, and coping strategies.
    2. IF the user asks about trivia, coding, politics, math, or general knowledge, YOU MUST REFUSE nicely and pivot back to their feelings.
    3. Keep your reply under 2 short sentences (Max 25 words).
    4. 🚨 CRITICAL RULE: You MUST write your response ONLY in pure English. Do NOT output any foreign scripts.
    """

    english_reply = ""

    # 🚀 PLAN A: Try the massive Gemma 4 model
    try:
        if not gemma_client: raise ValueError("Client offline.")
        
        chat_completion = gemma_client.chat.completions.create(
            model="google/gemma-4-31b-it:free", # 🚀 FIXED: Correct OpenRouter ID
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": enforced_input}
            ],
            temperature=0.7,
            max_tokens=60
        )
        english_reply = chat_completion.choices[0].message.content
        print("✅ Response generated by: GEMMA 4 31B (Plan A)")

    except Exception as primary_error:
        print(f"⚠️ Gemma 4 Failed ({primary_error}). Initiating Gemma 3 Failover...")
        
        # 🚀 PLAN B: Fallback to the highly stable, free Gemma 3 model
        try:
            if not gemma_client: raise ValueError("Client offline.")
            
            chat_completion = gemma_client.chat.completions.create(
                model="google/gemma-3-27b-it:free", # 🚀 FIXED: Upgraded Fallback
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": enforced_input}
                ],
                temperature=0.7,
                max_tokens=60
            )
            english_reply = chat_completion.choices[0].message.content
            print("✅ Response generated by: GEMMA 3 27B (Plan B)")
            
        except Exception as backup_error:
            # 💥 PLAN C: Total network failure.
            print(f"❌ Both Gemma models failed: {backup_error}")
            english_reply = "I am having a connection issue right now. Please remember you are not alone."

    if english_reply:
         english_reply = english_reply.replace('*', '').strip()
         
    if user_lang != 'en' and "connection issue" not in english_reply:
        try:
            return GoogleTranslator(source='en', target=user_lang).translate(english_reply)
        except:
            pass
            
    return english_reply